# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d7c94a236757dbef18eada4b44238d1dc06b0d3de81dd2843040a0e0b0c1635c3ef8ff6e47320da981808ef4fc047e87dfb188de49d30a5ab608470af67ce1c

test:
  secret_key_base: 81f3db734465690d847c096a83ee2dd62525d7d32c93c8055cac67171995148317e080f09575c53f21ff30e9a0ab9b34a6322eca0d9555ff0eb2485c11b5c18e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
